### PR TITLE
Fix solved problems not updating on team join

### PR DESCRIPTION
**Pull request by hiliang-cmu**
Cache was not invalidated for list of solved problems for both joining
player and team after `join_team` event, now forces refresh.

Original issue reproduction:
1. Create account and `team1` as `leader1`.
2. Create account as `player2` without joining team.
3. Solve `problem-A` as `player2`
4. Join `team1` as `player2`.

At this point, all members of `team1` do not see `problem-A` as solved. This
would not be resolved until a new correct flag is able to be submitted (past
cached problem-locked and already-solved limitations).

### CODE REVIEW

**Comment by hiliang-cmu** [comment]
Updated with more cache invalidations. Successful tested multiple rounds.

**Comment by hiliang-cmu** [comment]
Mis-merged that branch meh...

**Comment by maverickwoo** [comment]
I have just tested a95608c and I think I found two bugs, one persistent and one temporal.

1. (persistent) After the latest commit, the problems are opened as expected for both `leader1` and `player2`. However, the scoreboard still shows  `player2` as a separate team even though `player2` has joined `team1` already.

2. (temporal) After events 1-4 above, use `leader1` to solve a problem *different* from the problem `player2` solved in the first place. The number of solves displayed on the Problems page using `leader1` is wrong *at first*, showing `0` for the problem that was just solved by `leader1`. However, after a few reloads of the page, the number of solves becomes correct. I am not sure whether this is because I reloaded a few times or because some amount of time has passed after I reloaded the page a few times in the browser.

Can we please fix at least the persistent bug 1? Thanks!

**Comment by hiliang-cmu** [comment]
I was initially unsure about it, but think perhaps the best approach is to nuke _every_ cached item for: 

- `tid`, 
- `uid`,
- `player2` original `tid`

**Comment by maverickwoo** [comment]
Hmm... it seems the diff inside a95608c and inside c86fb9a are the same?
```
$ diff <(git show a95608c) <(git show c86fb9a)
1c1
< commit a95608c97f5f80a539753675fb8ff72af9532fd5
---
> commit c86fb9a85a6e447232b757d9129f52382a4ab455
```

**Comment by hiliang-cmu** [comment]
1. Is resolved by virtue of empty teams now being ignored on any team-getting functions including scoreboard. The scoreboard is updated every 60s by the stats ctf-daemon. 

2. I have been unable to replicate. This should be addressed already by the cache invalidation here: https://github.com/picoCTF/picoCTF/blob/ae0b4fcc0bdedafe45008d5a42e7047c8a07363d/picoCTF-web/api/problem.py#L471 though the stats ctf-daemon should likewise pick it up after a while here: https://github.com/picoCTF/picoCTF/blob/ae0b4fcc0bdedafe45008d5a42e7047c8a07363d/picoCTF-web/daemons/cache_stats.py#L35

**Pull request merged**
