### PR TITLE
WIP: Force line endings

### LINKED ISSUE #250: Ansible should fail early by checking shell script corruption due to autocrlf
I propose we add an ansible step to in the very beginning of provisioning to check if one of our shell scripts is corrupted due to autocrlf. The step should cause a fatal error so that the rest of the provisioning is stopped.

For context, we routinely run into Windows users who could not follow the clone command we spelled out. This is understandable. However, the failed provisioning is too subtle for a first-time user to discern. Having this step should make the failure (and its cause) very obvious.

### PR DESCRIPTION
**Pull request by syreal17**
With this .gitattributes files, Windows users should be able to successfully deploy the picoCTF platform regardless of their autocrlf settings.

EDIT: Need a reviewer who can test deployment on Windows easily (You've deployed picoCTF platform successfully on Windows)

Resolves #250

### CODE REVIEW

**Comment by syreal17** [comment]
The png line is just preserving what was in .gitattributes before. 

`*.tf		text eol=lf`Is an example of how we could make our intentions clearer with the file types and git's handling of line endings. However, since `*		text=auto` actually does fix #250, I thought we could integrate that change as soon as possible.

**Comment by dmartin** [comment]
I tested on Windows w/ git bash (core.autocrlf=true), Vagrant and VirtualBox.

It seemed like the problems loaded correctly (if I sshed into the shell VM using the private key, I could run `sudo shell_manager status` and see them with 2 deployed instances), but I wasn't able to ssh into the shell VM using password auth (`vagrant`/`vagrant`), so the problems weren't getting loaded into the web interface.

**Comment by syreal17** [comment]
Thanks for the test run. I'll probably put a bookmark in this for a bit as I'm working on things related to the web server getting the problem metadata from the shell server (#38, #147, #283) and I may discover some useful things along the way for this issue.

**Comment by archang31** [comment]
I recently encountered the exact scenario as below (Windows, git bash, verify problems load using `vagrant ssh` but cannot ssh directly into shell so web is unable to load problems). Is there any workaround for or update to this issue?

> I tested on Windows w/ git bash (core.autocrlf=true), Vagrant and VirtualBox.
> 
> It seemed like the problems loaded correctly (if I sshed into the shell VM using the private key, I could run `sudo shell_manager status` and see them with 2 deployed instances), but I wasn't able to ssh into the shell VM using password auth (`vagrant`/`vagrant`), so the problems weren't getting loaded into the web interface.

**Comment by syreal17** [comment]
@archang31 please see the comment by @maverickwoo here:
https://github.com/picoCTF/picoCTF/issues/68#issuecomment-346736808

This pull request is about automatically fixing this problem in spite of the Window's defaults, so that you can do a regular "git pull" instead of passing the switches referenced in the link provided. But for now, the provided link is the workaround.

**Comment by archang31** [comment]
thanks. I swear I did the `git clone -c core.autocrlf=false`, and was still getting this issue which is why I posted, but I clearly did not.  Sorry to waste your time.

> @archang31 please see the comment by @maverickwoo here:
> [#68 (comment)](https://github.com/picoCTF/picoCTF/issues/68#issuecomment-346736808)
> 
> This pull request is about automatically fixing this problem in spite of the Window's defaults, so that you can do a regular "git pull" instead of passing the switches referenced in the link provided. But for now, the provided link is the workaround.

**Comment by syreal17** [comment]
@archang31 no worries man! It is encouraging to see people using our platform and I could only answer your question so quickly because it has happened to many people in the past! I don't expect you to comb through all the hundreds on comments on various PR's and issues, etc. Would love to see you in our Discord server soon! https://discord.gg/pbdQQ7h (also listed in our top level README.md) Cheers!

**Comment by dmartin** [comment]
Closing in favor of #468.

**Pull request closed without merging**
