### PR TITLE
ansible deployment updates for AWS

### PR DESCRIPTION
**Pull request by mikea1729**
Includes:
* fixes for deploying web and db roles on separate hosts
* fixes/cleanup to the remote_testing template
* added remote_aws template mirroring the remote_testing template with minor changes
* `mkdeploy.sh` script to build a git bundle or zip to be deployed via "push"
* `rekey.py` to generate new keys and rekey the vault containing them

Tested deploying to AWS a few times.  @al3xfulton will make sure there are no major issues deploying real problems on the AWS instances.  First web user registered is user/pass: `user1` / `user1`

If someone can double check that I haven't messed up the normal vagrant development workflow somehow that'd be helpful.

This PR at creation time is live on AWS at:
```
[db]
pico_db     ansible_connection=local    hostname=pico-2018-db-1 ansible_host=ec2-18-222-250-51.us-east-2.compute.amazonaws.com on_aws=False

[shell]
pico_shell1   ansible_connection=local    hostname=pico-2018-shell-1 ansible_host=ec2-18-191-186-149.us-east-2.compute.amazonaws.com

[web]
pico_web     ansible_connection=local    hostname=pico-2018-web-1 ansible_host=ec2-18-222-129-59.us-east-2.compute.amazonaws.com
```
For those with AWS EC2 management access, this is the `deploy-testD-` set and the `deploy_tests` security group if you want to poke around.

### CODE REVIEW

**Comment by al3xfulton** [comment]
After a reasonable amount of testing, everything appears to be reacting in the same ways as other deployment techniques. Only notable difference seems to be the use of the full aws url (ie ec2-18-191-186-149.us-east-2.compute.amazonaws.com) when specifying the server/port pairs. Functionally the same, but much less clean that a straight IP address.

**Comment by maverickwoo** [comment]
I have tested this locally and local deployment seems to continue working well.

Can @al3xfulton comment on the AWS side? (Is your concern on AWS URL addressed?)

Thanks!

**Comment by al3xfulton** [comment]
I went into the AWS instance and replaced the hostname in `/opt/hacksport/config.json` with the appropriate IP address instead of long AWS URL, while the replacement occurs as expected within the questions going to that IP address does not work as intended otherwise. 

After thinking about it a bit more, @mikea1729 will the AWS hostname correctly populate when we change to our own domain like last year (ie shell.pico2017.com)? If thats the case this is probably a moot point as that is plenty clean enough for a public deployment.

**Comment by mikea1729** [comment]
@al3xfulton 
> while the replacement occurs as expected within the questions going to that IP address does not work as intended otherwise.
It's probably not reachable on the testing setup.  The IP should work fine for the real deployment

> will the AWS hostname correctly populate when we change to our own domain like last year (ie shell.pico2017.com)
It would have but only if the DNS was setup prior to deployment and we used that domain name for deployment. - past tense, because the commit added during our last meeting (f8fb7e9) made it so an IP address is always used.  Not that we couldn't easily change this (again)

**Comment by maverickwoo** [comment]
I now have positive testing confirmations from @al3xfulton, @hiliang-cmu, and myself. Merging.

Huge thanks goes to @mikea1729!

**Pull request merged**
