### PR TITLE
Conditional removal of team members

### LINKED ISSUE #432: Allow team captain to kick team members who have not made any submissions
Should address majority of scenarios of legitimately removing a team member without being abuse-able towards someone who has made contributions

### PR DESCRIPTION
**Pull request by dmartin**
Allows team members to leave / be kicked as long as they haven't submitted any flags.

* Users who are kicked or elect to leave a team are placed back on their self-team, bringing along any group memberships they obtained along the way.
* Only team creators can kick other members
* Anyone can leave, team creators can only leave if they are the only remaining member
* The team creator is labeled as the captain in the member list
* If a custom (non-self) team hits 0 members, it is removed

Resolves #432

### CODE REVIEW

**Comment by maverickwoo** [comment]
May I ask why do we use the definition "haven't submitted a *correct* flag"? Wouldn't the definition of "haven't submitted any flag" be more natural? Just curious.

**Comment by dmartin** [comment]
@hiliang-cmu Should be good for re-review with the changes we discussed.

**Comment by hiliang-cmu** [comment]
LGTM then. Any other conceptual changes based on any of our convos before merge?

**Comment by dmartin** [comment]
@hiliang-cmu Don’t think so, changes lgtm

**Pull request merged**
