### PR TITLE
yapf google

### PR DESCRIPTION
**Pull request by hiliang-cmu**
`yapf --style google`

### CODE REVIEW

**Comment by hiliang-cmu** [comment]
Squashed

**Comment by maverickwoo** [comment]
I just ran `yapf -p -i -r --style google .` in the root directory of 4d741c03 and eight files were modified as a result. Can you please figure out why? (For example, can you repro this?)

Also, can you please add a minimal `.style.yapf` to the root directory of the project so that we can be sure that everyone uses `google` as the default style? Maybe something like:
```
[style]
based_on_style = google
```

Thanks!

P.S. The acceptance criteria for this PR will be:
1. `yapf -p -i -r .` results in a no-op.
2. `vagrant destroy; vagrant up` results in a what-appears-to-be a working installation (can register a few users, can login, can see a few problems, etc. The checking will be "best effort" only. :>)

Some details:
```
$ git reset --hard
HEAD is now at 4d741c03 yapf google
$ yapf -p -i -r --style google .
$ git status -s
 M picoCTF-shell/hacksport/deploy.py
 M picoCTF-shell/shell_manager/bundle.py
 M picoCTF-shell/shell_manager/package.py
 M picoCTF-web/api/achievement.py
 M picoCTF-web/api/api_manager.py
 M picoCTF-web/api/problem.py
 M picoCTF-web/api/stats.py
 M picoCTF-web/test/unit_tests/problem_test.py
$ python --version
Python 3.6.5
$ yapf --version
yapf 0.22.0
```

Example diff:
```diff
$ git diff picoCTF-web/api/api_manager.py
diff --git a/picoCTF-web/api/api_manager.py b/picoCTF-web/api/api_manager.py
index 7bd6ba72..cae894a9 100755
--- a/picoCTF-web/api/api_manager.py
+++ b/picoCTF-web/api/api_manager.py
@@ -113,9 +113,9 @@ def list_problems(args):
     #TODO: This could be improved
     problems = api.problem.get_all_problems(show_disabled=True)
     for problem in problems:
-        print("{} ({}) - {} points".format(problem["name"], "disabled"
-                                           if problem["disabled"] else
-                                           "enabled", problem["score"]))
+        print("{} ({}) - {} points".format(
+            problem["name"], "disabled"
+            if problem["disabled"] else "enabled", problem["score"]))
 
 
 def clear_collections(args):
```

**Comment by hiliang-cmu** [comment]
A newer yapf was released 15 days ago, will re-process this.

**Comment by maverickwoo** [comment]
Criteria 1 checks out. I am testing criteria 2 right now and I will merge if that passes also.

You can add a pre-commit hook task to the project board. Thanks!

**Comment by maverickwoo** [comment]
I have tested criteria 2 as well and the basic functions appear to be working properly. I am merging this.

**Pull request merged**
